name: Build Connecto APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract project
        run: |
          mkdir app
          unzip connecto_app_flutter.zip -d app

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'

      - name: Build APK
        run: |
          cd app
          flutter pub get
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Connecto-APK
          path: app/build/app/outputs/flutter-apk/app-release.apk
          
